### ISSUE TITLE
Calling send_request without "from" gives a wrong error message

### ISSUE THREAD

**Issue by dappelt** [interledgerjs/ilp-plugin-payment-channel-framework#9]
Calling `send_request` with:
```
[
  {
    "ledger": "g.crypto.paychan.framework.",
    "to": "g.crypto.paychan.framework.server",
    "ilp": "ARwAAAAAB1TUwA5nLnVzLm5leHVzLmJvYgMEEEEA"
  }
]
```

Result: 
```
{
    "id": "InvalidFieldsError",
    "message": "must have a destination (.to)"
}
```

To fix this error, `from: ...` has to be added to the request, which does not make much sense given the error message and the request has already a to field.

When looking at a debug track, it becomes apparent what goes wrong:
```
[api]   ilp-plugin-virtual incoming send_request from [ 'https://wallet2.example/api/pseers/rpc' ] with [ { ledger: 'g.crypto.paychan.framework.',
[api]     to: 'g.crypto.paychan.framework.server',
[api]     ilp: '...' } ] +0ms
[api] validate incoming
[api] ASDF { ledger: 'g.crypto.paychan.framework.',
[api]   to: 'g.crypto.paychan.framework.server',
[api]   ilp: '...' }
[api] validate outgoing
[api] ASDF { ledger: 'g.crypto.paychan.framework.',
[api]   to: undefined,
[api]   from: 'g.crypto.paychan.framework.server',
[api]   ilp: '...' }
```

The `from` field from the incoming message is used to set the `to` field in the outgoing message. Since `from` is undefined in the incoming message, `to` becomes undefined in the outoing message.

We might want to remove `.to` and `.from` from the message to avoid such bugs. In a bilateral trustline, these field are redundant.
 
Related to interledger/rfcs/issues/234 (cc: @sharafian @michielbdejong)

**Comment by michielbdejong** [comment]
> We might want to remove .to and .from from the message to avoid such bugs. In a bilateral trustline, these field are redundant.

Let's try to stop our stream of continuous protocol improvements. Let's save that for version 0.2 (e.g. in January 2018) of the rpc protocol, and concentrate on getting version 0.1 first.

I think the proper solution here would be to change [these lines](https://github.com/interledgerjs/ilp-plugin-payment-channel-framework/blob/master/src/lib/plugin.js#L240-L241) to something like
```js
  from: getAccount(),
  to: getPeerAccount(),
```

The function `getPeerAccount` [already exists](https://github.com/interledgerjs/ilp-plugin-payment-channel-framework/blob/master/src/lib/plugin.js#L114).

**Comment by dappelt** [comment]
We started only recently to standardise the plugin RPC API and the RFC is still in a rough state. I disagree with delaying necessary changes in this inmature state. Once we reach a stable version we can think about freezing the RFC.

**Comment by michielbdejong** [comment]
I know of no necessary changes, I only know of two proposed simplifications, and one non-critical improvement. The current version is implemented and works without those simplifications and without this improvement. Proposed changes for v0.2 are:
* (simplification) remove .ledger (all agreed)
* (simplification) remove .from and .to (no consensus on this, see [Stefan's objection](https://github.com/interledger/rfcs/issues/234#issuecomment-315334157))
* (improvement, non-critical) send finalization (fulfill/reject/cancel) in response to send_transfer (no consensus on this, see [Ben's objection](https://github.com/interledger/rfcs/issues/235#issuecomment-313646202))

So for now, until we know what the next rpc protocol version will look like, let's stick to the current version in our code. The last thing we want is implement a different version in each component :)

**Comment by sharafian** [comment]
We don't have the RPC api implemented in that many places yet. I agree that we should not put in any meaningful changes yet, but the `to`, `from`, and `ledger` fields are causing problems in all the current implementations, and we're not getting any benefit from using them. We should at least tell new implementations not to require these fields, even if they don't send them, although I still think the best option is to take them out while it's still easy

**Comment by emschwartz** [comment]
What about making it so the components don't check those fields (or don't complain if they're not there) but still send them out?

**Comment by sharafian** [comment]
That's a good start, but whenever we send something there's going to be _somebody_ who either validates or relies on it, so it becomes a breaking change to remove those fields. We could explicitly make it optional in the spec, but then that's a spec change

**Comment by emschwartz** [comment]
Yeah, whenever it's removed it would be breaking. However, it sounds like removing the checks would solve the immediate issues you've been seeing with those fields and make the version that doesn't check them compatible with both the previous version that requires them and the next version that doesn't include them at all.

In general, when we can I think it would be good to make this kind of "rolling update", where we first have a version that accepts the new format/feature but doesn't use it yet and then the next version would use the feature.
